package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="cargo"
    ,schema="public"
)
public class Cargo  implements java.io.Serializable {


     private int idcargo;
     private String nombrecargo;
     private BigDecimal sueldo;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Cargo() {
    }

	
    public Cargo(int idcargo) {
        this.idcargo = idcargo;
    }
    public Cargo(int idcargo, String nombrecargo, BigDecimal sueldo, Set<Empleado> empleados) {
       this.idcargo = idcargo;
       this.nombrecargo = nombrecargo;
       this.sueldo = sueldo;
       this.empleados = empleados;
    }
   
     @Id 

    
    @Column(name="idcargo", nullable=false)
    public int getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(int idcargo) {
        this.idcargo = idcargo;
    }

    
    @Column(name="nombrecargo", length=50)
    public String getNombrecargo() {
        return this.nombrecargo;
    }
    
    public void setNombrecargo(String nombrecargo) {
        this.nombrecargo = nombrecargo;
    }

    
    @Column(name="sueldo", precision=10)
    public BigDecimal getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(BigDecimal sueldo) {
        this.sueldo = sueldo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargo")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


