package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,schema="public"
)
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private String nombredepartamento;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Departamento(int iddepartamento, String nombredepartamento, Set<Municipio> municipios) {
       this.iddepartamento = iddepartamento;
       this.nombredepartamento = nombredepartamento;
       this.municipios = municipios;
    }
   
     @Id 

    
    @Column(name="iddepartamento", nullable=false)
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }

    
    @Column(name="nombredepartamento", length=50)
    public String getNombredepartamento() {
        return this.nombredepartamento;
    }
    
    public void setNombredepartamento(String nombredepartamento) {
        this.nombredepartamento = nombredepartamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


