package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,schema="public"
)
public class Empleado  implements java.io.Serializable {


     private String duiempleado;
     private Cargo cargo;
     private Municipio municipio;
     private String nombreempleado;
     private String apellidoempleado;
     private String direccionempleado;
     private String telefonoempleado;
     private String estadoempleado;
     private Set<Lavado> lavados = new HashSet<Lavado>(0);

    public Empleado() {
    }

	
    public Empleado(String duiempleado) {
        this.duiempleado = duiempleado;
    }
    public Empleado(String duiempleado, Cargo cargo, Municipio municipio, String nombreempleado, String apellidoempleado, String direccionempleado, String telefonoempleado, String estadoempleado, Set<Lavado> lavados) {
       this.duiempleado = duiempleado;
       this.cargo = cargo;
       this.municipio = municipio;
       this.nombreempleado = nombreempleado;
       this.apellidoempleado = apellidoempleado;
       this.direccionempleado = direccionempleado;
       this.telefonoempleado = telefonoempleado;
       this.estadoempleado = estadoempleado;
       this.lavados = lavados;
    }
   
     @Id 

    
    @Column(name="duiempleado", nullable=false, length=10)
    public String getDuiempleado() {
        return this.duiempleado;
    }
    
    public void setDuiempleado(String duiempleado) {
        this.duiempleado = duiempleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcargo")
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmunicipio")
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

    
    @Column(name="nombreempleado", length=50)
    public String getNombreempleado() {
        return this.nombreempleado;
    }
    
    public void setNombreempleado(String nombreempleado) {
        this.nombreempleado = nombreempleado;
    }

    
    @Column(name="apellidoempleado", length=50)
    public String getApellidoempleado() {
        return this.apellidoempleado;
    }
    
    public void setApellidoempleado(String apellidoempleado) {
        this.apellidoempleado = apellidoempleado;
    }

    
    @Column(name="direccionempleado", length=100)
    public String getDireccionempleado() {
        return this.direccionempleado;
    }
    
    public void setDireccionempleado(String direccionempleado) {
        this.direccionempleado = direccionempleado;
    }

    
    @Column(name="telefonoempleado", length=9)
    public String getTelefonoempleado() {
        return this.telefonoempleado;
    }
    
    public void setTelefonoempleado(String telefonoempleado) {
        this.telefonoempleado = telefonoempleado;
    }

    
    @Column(name="estadoempleado", length=3)
    public String getEstadoempleado() {
        return this.estadoempleado;
    }
    
    public void setEstadoempleado(String estadoempleado) {
        this.estadoempleado = estadoempleado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set<Lavado> getLavados() {
        return this.lavados;
    }
    
    public void setLavados(Set<Lavado> lavados) {
        this.lavados = lavados;
    }




}


