package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lavado generated by hbm2java
 */
@Entity
@Table(name="lavado"
    ,schema="public"
)
public class Lavado  implements java.io.Serializable {


     private int idlavado;
     private Empleado empleado;
     private Precioservicio precioservicio;
     private Vehiculo vehiculo;
     private Date fecha;
     private String estado;

    public Lavado() {
    }

	
    public Lavado(int idlavado) {
        this.idlavado = idlavado;
    }
    public Lavado(int idlavado, Empleado empleado, Precioservicio precioservicio, Vehiculo vehiculo, Date fecha, String estado) {
       this.idlavado = idlavado;
       this.empleado = empleado;
       this.precioservicio = precioservicio;
       this.vehiculo = vehiculo;
       this.fecha = fecha;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="idlavado", nullable=false)
    public int getIdlavado() {
        return this.idlavado;
    }
    
    public void setIdlavado(int idlavado) {
        this.idlavado = idlavado;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="duiempleado")
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idprecioservicio")
    public Precioservicio getPrecioservicio() {
        return this.precioservicio;
    }
    
    public void setPrecioservicio(Precioservicio precioservicio) {
        this.precioservicio = precioservicio;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="placavehiculo")
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", length=3)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


