package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="municipio"
    ,schema="public"
)
public class Municipio  implements java.io.Serializable {


     private int idmunicipio;
     private Departamento departamento;
     private String nombremunicipio;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Municipio() {
    }

	
    public Municipio(int idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Municipio(int idmunicipio, Departamento departamento, String nombremunicipio, Set<Empleado> empleados) {
       this.idmunicipio = idmunicipio;
       this.departamento = departamento;
       this.nombremunicipio = nombremunicipio;
       this.empleados = empleados;
    }
   
     @Id 

    
    @Column(name="idmunicipio", nullable=false)
    public int getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(int idmunicipio) {
        this.idmunicipio = idmunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddepartamento")
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="nombremunicipio", length=50)
    public String getNombremunicipio() {
        return this.nombremunicipio;
    }
    
    public void setNombremunicipio(String nombremunicipio) {
        this.nombremunicipio = nombremunicipio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipio")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


