package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Precioservicio generated by hbm2java
 */
@Entity
@Table(name="precioservicio"
    ,schema="public"
)
public class Precioservicio  implements java.io.Serializable {


     private int idprecioservicio;
     private Servicios servicios;
     private Tipovehiculo tipovehiculo;
     private BigDecimal precio;
     private Set<Lavado> lavados = new HashSet<Lavado>(0);

    public Precioservicio() {
    }

	
    public Precioservicio(int idprecioservicio) {
        this.idprecioservicio = idprecioservicio;
    }
    public Precioservicio(int idprecioservicio, Servicios servicios, Tipovehiculo tipovehiculo, BigDecimal precio, Set<Lavado> lavados) {
       this.idprecioservicio = idprecioservicio;
       this.servicios = servicios;
       this.tipovehiculo = tipovehiculo;
       this.precio = precio;
       this.lavados = lavados;
    }
   
     @Id 

    
    @Column(name="idprecioservicio", nullable=false)
    public int getIdprecioservicio() {
        return this.idprecioservicio;
    }
    
    public void setIdprecioservicio(int idprecioservicio) {
        this.idprecioservicio = idprecioservicio;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idservicios")
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipovehiculo")
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }

    
    @Column(name="precio", precision=3)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="precioservicio")
    public Set<Lavado> getLavados() {
        return this.lavados;
    }
    
    public void setLavados(Set<Lavado> lavados) {
        this.lavados = lavados;
    }




}


