package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipovehiculo generated by hbm2java
 */
@Entity
@Table(name="tipovehiculo"
    ,schema="public"
)
public class Tipovehiculo  implements java.io.Serializable {


     private int idtipovehiculo;
     private String descripcionvehiculo;
     private Set<Precioservicio> precioservicios = new HashSet<Precioservicio>(0);
     private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

    public Tipovehiculo() {
    }

	
    public Tipovehiculo(int idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }
    public Tipovehiculo(int idtipovehiculo, String descripcionvehiculo, Set<Precioservicio> precioservicios, Set<Vehiculo> vehiculos) {
       this.idtipovehiculo = idtipovehiculo;
       this.descripcionvehiculo = descripcionvehiculo;
       this.precioservicios = precioservicios;
       this.vehiculos = vehiculos;
    }
   
     @Id 

    
    @Column(name="idtipovehiculo", nullable=false)
    public int getIdtipovehiculo() {
        return this.idtipovehiculo;
    }
    
    public void setIdtipovehiculo(int idtipovehiculo) {
        this.idtipovehiculo = idtipovehiculo;
    }

    
    @Column(name="descripcionvehiculo", length=50)
    public String getDescripcionvehiculo() {
        return this.descripcionvehiculo;
    }
    
    public void setDescripcionvehiculo(String descripcionvehiculo) {
        this.descripcionvehiculo = descripcionvehiculo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipovehiculo")
    public Set<Precioservicio> getPrecioservicios() {
        return this.precioservicios;
    }
    
    public void setPrecioservicios(Set<Precioservicio> precioservicios) {
        this.precioservicios = precioservicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipovehiculo")
    public Set<Vehiculo> getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set<Vehiculo> vehiculos) {
        this.vehiculos = vehiculos;
    }




}


