package modelo;
// Generated 04-27-2021 08:40:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,schema="public"
)
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private Cliente cliente;
     private Tipovehiculo tipovehiculo;
     private String marca;
     private String color;
     private Set<Lavado> lavados = new HashSet<Lavado>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String placa) {
        this.placa = placa;
    }
    public Vehiculo(String placa, Cliente cliente, Tipovehiculo tipovehiculo, String marca, String color, Set<Lavado> lavados) {
       this.placa = placa;
       this.cliente = cliente;
       this.tipovehiculo = tipovehiculo;
       this.marca = marca;
       this.color = color;
       this.lavados = lavados;
    }
   
     @Id 

    
    @Column(name="placa", nullable=false, length=8)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="duicliente")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idtipovehiculo")
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }

    
    @Column(name="marca", length=15)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="color", length=15)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set<Lavado> getLavados() {
        return this.lavados;
    }
    
    public void setLavados(Set<Lavado> lavados) {
        this.lavados = lavados;
    }




}


